/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SeatsRouteImport } from './routes/seats'
import { Route as SearchResultsRouteImport } from './routes/search-results'
import { Route as ManageBookingRouteImport } from './routes/manage-booking'
import { Route as HireFleetRouteImport } from './routes/hire-fleet'
import { Route as HireConfirmationRouteImport } from './routes/hire-confirmation'
import { Route as HireCheckoutRouteImport } from './routes/hire-checkout'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatsRoute = SeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchResultsRoute = SearchResultsRouteImport.update({
  id: '/search-results',
  path: '/search-results',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageBookingRoute = ManageBookingRouteImport.update({
  id: '/manage-booking',
  path: '/manage-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const HireFleetRoute = HireFleetRouteImport.update({
  id: '/hire-fleet',
  path: '/hire-fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const HireConfirmationRoute = HireConfirmationRouteImport.update({
  id: '/hire-confirmation',
  path: '/hire-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const HireCheckoutRoute = HireCheckoutRouteImport.update({
  id: '/hire-checkout',
  path: '/hire-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/hire-checkout': typeof HireCheckoutRoute
  '/hire-confirmation': typeof HireConfirmationRoute
  '/hire-fleet': typeof HireFleetRoute
  '/manage-booking': typeof ManageBookingRoute
  '/search-results': typeof SearchResultsRoute
  '/seats': typeof SeatsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/hire-checkout': typeof HireCheckoutRoute
  '/hire-confirmation': typeof HireConfirmationRoute
  '/hire-fleet': typeof HireFleetRoute
  '/manage-booking': typeof ManageBookingRoute
  '/search-results': typeof SearchResultsRoute
  '/seats': typeof SeatsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/hire-checkout': typeof HireCheckoutRoute
  '/hire-confirmation': typeof HireConfirmationRoute
  '/hire-fleet': typeof HireFleetRoute
  '/manage-booking': typeof ManageBookingRoute
  '/search-results': typeof SearchResultsRoute
  '/seats': typeof SeatsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/confirmation'
    | '/hire-checkout'
    | '/hire-confirmation'
    | '/hire-fleet'
    | '/manage-booking'
    | '/search-results'
    | '/seats'
    | '/sign-in'
    | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/confirmation'
    | '/hire-checkout'
    | '/hire-confirmation'
    | '/hire-fleet'
    | '/manage-booking'
    | '/search-results'
    | '/seats'
    | '/sign-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/confirmation'
    | '/hire-checkout'
    | '/hire-confirmation'
    | '/hire-fleet'
    | '/manage-booking'
    | '/search-results'
    | '/seats'
    | '/sign-in'
    | '/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfirmationRoute: typeof ConfirmationRoute
  HireCheckoutRoute: typeof HireCheckoutRoute
  HireConfirmationRoute: typeof HireConfirmationRoute
  HireFleetRoute: typeof HireFleetRoute
  ManageBookingRoute: typeof ManageBookingRoute
  SearchResultsRoute: typeof SearchResultsRoute
  SeatsRoute: typeof SeatsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seats': {
      id: '/seats'
      path: '/seats'
      fullPath: '/seats'
      preLoaderRoute: typeof SeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-results': {
      id: '/search-results'
      path: '/search-results'
      fullPath: '/search-results'
      preLoaderRoute: typeof SearchResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-booking': {
      id: '/manage-booking'
      path: '/manage-booking'
      fullPath: '/manage-booking'
      preLoaderRoute: typeof ManageBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-fleet': {
      id: '/hire-fleet'
      path: '/hire-fleet'
      fullPath: '/hire-fleet'
      preLoaderRoute: typeof HireFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-confirmation': {
      id: '/hire-confirmation'
      path: '/hire-confirmation'
      fullPath: '/hire-confirmation'
      preLoaderRoute: typeof HireConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-checkout': {
      id: '/hire-checkout'
      path: '/hire-checkout'
      fullPath: '/hire-checkout'
      preLoaderRoute: typeof HireCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ConfirmationRoute: ConfirmationRoute,
  HireCheckoutRoute: HireCheckoutRoute,
  HireConfirmationRoute: HireConfirmationRoute,
  HireFleetRoute: HireFleetRoute,
  ManageBookingRoute: ManageBookingRoute,
  SearchResultsRoute: SearchResultsRoute,
  SeatsRoute: SeatsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
